import { NavBar } from '@/components/Nav/NavBar'
import { Menu } from '@/components/Nav/Menu'
import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <NavBar />
        <Menu />
        {children}
      </body>
    </html>
  )
}
